name: holcomb_tree_trail
description: "A project to educate and showcase the Holcomb Tree Trail arboretum."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  firebase_core: ^4.2.0
  google_fonts: ^7.0.0
  flutter_markdown_plus: ^1.0.5
  yaml: ^3.1.3
  flutter:
    sdk: flutter
  firebase_storage: ^13.0.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/tree_trail_logo.png
    - lib/assets/HTT_farm_view.png
    - lib/assets/ABOUT_THE_TRAIL.txt
    - lib/assets/VISITOR_INFO.txt
    - lib/assets/rotating_leaf.gif